# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

authConfig: Optional[str]
"""
Authentication configuration
"""

host: Optional[str]
"""
The hostname to use to connect to the clickhouse instance
"""

port: Optional[int]
"""
The port to use to connect to the clickhouse instance
"""

protocol: Optional[str]
"""
The protocol to use to connect to clickhouse instance. Valid options are: native, nativesecure, http, https
"""

tlsConfig: Optional[str]
"""
TLS configuration options
"""

