# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

import types

__config__ = pulumi.Config('clickhousedbops')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def auth_config(self) -> Optional[str]:
        """
        Authentication configuration
        """
        return __config__.get('authConfig')

    @_builtins.property
    def host(self) -> Optional[str]:
        """
        The hostname to use to connect to the clickhouse instance
        """
        return __config__.get('host')

    @_builtins.property
    def port(self) -> Optional[int]:
        """
        The port to use to connect to the clickhouse instance
        """
        return __config__.get_int('port')

    @_builtins.property
    def protocol(self) -> Optional[str]:
        """
        The protocol to use to connect to clickhouse instance. Valid options are: native, nativesecure, http, https
        """
        return __config__.get('protocol')

    @_builtins.property
    def tls_config(self) -> Optional[str]:
        """
        TLS configuration options
        """
        return __config__.get('tlsConfig')

