// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhousedbops
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Clickhousedbops = Pulumi.Clickhousedbops;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var roleToUser = new Clickhousedbops.GrantRole("role_to_user", new()
    ///     {
    ///         ClusterName = "cluster",
    ///         RoleName = "myrole",
    ///         GranteeUserName = "myuser",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [ClickhousedbopsResourceType("clickhousedbops:index/grantRole:GrantRole")]
    public partial class GrantRole : global::Pulumi.CustomResource
    {
        /// <summary>
        /// If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        /// </summary>
        [Output("adminOption")]
        public Output<bool> AdminOption { get; private set; } = null!;

        /// <summary>
        /// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        /// This field must be left null when using a ClickHouse Cloud cluster.
        /// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        /// </summary>
        [Output("clusterName")]
        public Output<string?> ClusterName { get; private set; } = null!;

        /// <summary>
        /// Name of the `role` to grant `role_name` to.
        /// </summary>
        [Output("granteeRoleName")]
        public Output<string?> GranteeRoleName { get; private set; } = null!;

        /// <summary>
        /// Name of the `user` to grant `role_name` to.
        /// </summary>
        [Output("granteeUserName")]
        public Output<string?> GranteeUserName { get; private set; } = null!;

        /// <summary>
        /// Name of the role to be granted
        /// </summary>
        [Output("roleName")]
        public Output<string> RoleName { get; private set; } = null!;


        /// <summary>
        /// Create a GrantRole resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GrantRole(string name, GrantRoleArgs args, CustomResourceOptions? options = null)
            : base("clickhousedbops:index/grantRole:GrantRole", name, args ?? new GrantRoleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GrantRole(string name, Input<string> id, GrantRoleState? state = null, CustomResourceOptions? options = null)
            : base("clickhousedbops:index/grantRole:GrantRole", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GrantRole resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GrantRole Get(string name, Input<string> id, GrantRoleState? state = null, CustomResourceOptions? options = null)
        {
            return new GrantRole(name, id, state, options);
        }
    }

    public sealed class GrantRoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        /// </summary>
        [Input("adminOption")]
        public Input<bool>? AdminOption { get; set; }

        /// <summary>
        /// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        /// This field must be left null when using a ClickHouse Cloud cluster.
        /// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        /// <summary>
        /// Name of the `role` to grant `role_name` to.
        /// </summary>
        [Input("granteeRoleName")]
        public Input<string>? GranteeRoleName { get; set; }

        /// <summary>
        /// Name of the `user` to grant `role_name` to.
        /// </summary>
        [Input("granteeUserName")]
        public Input<string>? GranteeUserName { get; set; }

        /// <summary>
        /// Name of the role to be granted
        /// </summary>
        [Input("roleName", required: true)]
        public Input<string> RoleName { get; set; } = null!;

        public GrantRoleArgs()
        {
        }
        public static new GrantRoleArgs Empty => new GrantRoleArgs();
    }

    public sealed class GrantRoleState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        /// </summary>
        [Input("adminOption")]
        public Input<bool>? AdminOption { get; set; }

        /// <summary>
        /// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        /// This field must be left null when using a ClickHouse Cloud cluster.
        /// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        /// <summary>
        /// Name of the `role` to grant `role_name` to.
        /// </summary>
        [Input("granteeRoleName")]
        public Input<string>? GranteeRoleName { get; set; }

        /// <summary>
        /// Name of the `user` to grant `role_name` to.
        /// </summary>
        [Input("granteeUserName")]
        public Input<string>? GranteeUserName { get; set; }

        /// <summary>
        /// Name of the role to be granted
        /// </summary>
        [Input("roleName")]
        public Input<string>? RoleName { get; set; }

        public GrantRoleState()
        {
        }
        public static new GrantRoleState Empty => new GrantRoleState();
    }
}
