// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhousedbops
{
    /// <summary>
    /// You can use the `clickhousedbops.Setting` resource to manage the single `settings` of a `Setting Profile` in a `ClickHouse` instance.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Clickhousedbops = Pulumi.Clickhousedbops;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var setting1 = new Clickhousedbops.Setting("setting1", new()
    ///     {
    ///         SettingsProfileId = profile1.Id,
    ///         Name = "max_memory_usage",
    ///         Value = "1000",
    ///         Min = "100",
    ///         Max = "2000",
    ///         Writability = "CHANGEABLE_IN_READONLY",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [ClickhousedbopsResourceType("clickhousedbops:index/setting:Setting")]
    public partial class Setting : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        /// This field must be left null when using a ClickHouse Cloud cluster.
        /// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        /// </summary>
        [Output("clusterName")]
        public Output<string?> ClusterName { get; private set; } = null!;

        /// <summary>
        /// Max Value for the setting
        /// </summary>
        [Output("max")]
        public Output<string?> Max { get; private set; } = null!;

        /// <summary>
        /// Min Value for the setting
        /// </summary>
        [Output("min")]
        public Output<string?> Min { get; private set; } = null!;

        /// <summary>
        /// Name of the setting
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// ID of the settings profile
        /// </summary>
        [Output("settingsProfileId")]
        public Output<string> SettingsProfileId { get; private set; } = null!;

        /// <summary>
        /// Value for the setting
        /// </summary>
        [Output("value")]
        public Output<string?> Value { get; private set; } = null!;

        /// <summary>
        /// Writability attribute for the setting
        /// </summary>
        [Output("writability")]
        public Output<string?> Writability { get; private set; } = null!;


        /// <summary>
        /// Create a Setting resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Setting(string name, SettingArgs args, CustomResourceOptions? options = null)
            : base("clickhousedbops:index/setting:Setting", name, args ?? new SettingArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Setting(string name, Input<string> id, SettingState? state = null, CustomResourceOptions? options = null)
            : base("clickhousedbops:index/setting:Setting", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Setting resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Setting Get(string name, Input<string> id, SettingState? state = null, CustomResourceOptions? options = null)
        {
            return new Setting(name, id, state, options);
        }
    }

    public sealed class SettingArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        /// This field must be left null when using a ClickHouse Cloud cluster.
        /// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        /// <summary>
        /// Max Value for the setting
        /// </summary>
        [Input("max")]
        public Input<string>? Max { get; set; }

        /// <summary>
        /// Min Value for the setting
        /// </summary>
        [Input("min")]
        public Input<string>? Min { get; set; }

        /// <summary>
        /// Name of the setting
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the settings profile
        /// </summary>
        [Input("settingsProfileId", required: true)]
        public Input<string> SettingsProfileId { get; set; } = null!;

        /// <summary>
        /// Value for the setting
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        /// <summary>
        /// Writability attribute for the setting
        /// </summary>
        [Input("writability")]
        public Input<string>? Writability { get; set; }

        public SettingArgs()
        {
        }
        public static new SettingArgs Empty => new SettingArgs();
    }

    public sealed class SettingState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        /// This field must be left null when using a ClickHouse Cloud cluster.
        /// When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        /// </summary>
        [Input("clusterName")]
        public Input<string>? ClusterName { get; set; }

        /// <summary>
        /// Max Value for the setting
        /// </summary>
        [Input("max")]
        public Input<string>? Max { get; set; }

        /// <summary>
        /// Min Value for the setting
        /// </summary>
        [Input("min")]
        public Input<string>? Min { get; set; }

        /// <summary>
        /// Name of the setting
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// ID of the settings profile
        /// </summary>
        [Input("settingsProfileId")]
        public Input<string>? SettingsProfileId { get; set; }

        /// <summary>
        /// Value for the setting
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        /// <summary>
        /// Writability attribute for the setting
        /// </summary>
        [Input("writability")]
        public Input<string>? Writability { get; set; }

        public SettingState()
        {
        }
        public static new SettingState Empty => new SettingState();
    }
}
