// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("clickhousedbops");

/**
 * Authentication configuration
 */
export declare const authConfig: outputs.config.AuthConfig | undefined;
Object.defineProperty(exports, "authConfig", {
    get() {
        return __config.getObject<outputs.config.AuthConfig>("authConfig");
    },
    enumerable: true,
});

/**
 * The hostname to use to connect to the clickhouse instance
 */
export declare const host: string | undefined;
Object.defineProperty(exports, "host", {
    get() {
        return __config.get("host");
    },
    enumerable: true,
});

/**
 * The port to use to connect to the clickhouse instance
 */
export declare const port: number | undefined;
Object.defineProperty(exports, "port", {
    get() {
        return __config.getObject<number>("port");
    },
    enumerable: true,
});

/**
 * The protocol to use to connect to clickhouse instance. Valid options are: native, nativesecure, http, https
 */
export declare const protocol: string | undefined;
Object.defineProperty(exports, "protocol", {
    get() {
        return __config.get("protocol");
    },
    enumerable: true,
});

/**
 * TLS configuration options
 */
export declare const tlsConfig: outputs.config.TlsConfig | undefined;
Object.defineProperty(exports, "tlsConfig", {
    get() {
        return __config.getObject<outputs.config.TlsConfig>("tlsConfig");
    },
    enumerable: true,
});

