// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/LiHRaM/pulumi-clickhousedbops/sdk/go/clickhousedbops/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Authentication configuration
func GetAuthConfig(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhousedbops:authConfig")
}

// The hostname to use to connect to the clickhouse instance
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhousedbops:host")
}

// The port to use to connect to the clickhouse instance
func GetPort(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "clickhousedbops:port")
}

// The protocol to use to connect to clickhouse instance. Valid options are: native, nativesecure, http, https
func GetProtocol(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhousedbops:protocol")
}

// TLS configuration options
func GetTlsConfig(ctx *pulumi.Context) string {
	return config.Get(ctx, "clickhousedbops:tlsConfig")
}
