// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package clickhousedbops

import (
	"fmt"

	"github.com/LiHRaM/pulumi-clickhousedbops/sdk/go/clickhousedbops/internal"
	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "clickhousedbops:index/database:Database":
		r = &Database{}
	case "clickhousedbops:index/grantPrivilege:GrantPrivilege":
		r = &GrantPrivilege{}
	case "clickhousedbops:index/grantRole:GrantRole":
		r = &GrantRole{}
	case "clickhousedbops:index/role:Role":
		r = &Role{}
	case "clickhousedbops:index/setting:Setting":
		r = &Setting{}
	case "clickhousedbops:index/settingsProfile:SettingsProfile":
		r = &SettingsProfile{}
	case "clickhousedbops:index/settingsProfileAssociation:SettingsProfileAssociation":
		r = &SettingsProfileAssociation{}
	case "clickhousedbops:index/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:clickhousedbops" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/database",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/grantPrivilege",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/grantRole",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/setting",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/settingsProfile",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/settingsProfileAssociation",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"clickhousedbops",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"clickhousedbops",
		&pkg{version},
	)
}
