// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ProviderAuthConfig {
    /**
     * The password to use to authenticate to ClickHouse
     */
    password?: pulumi.Input<string>;
    /**
     * The authentication method to use
     */
    strategy: pulumi.Input<string>;
    /**
     * The username to use to authenticate to ClickHouse
     */
    username: pulumi.Input<string>;
}

export interface ProviderTlsConfig {
    /**
     * Skip TLS cert verification when using the https protocol. This is insecure!
     */
    insecureSkipVerify?: pulumi.Input<boolean>;
}
export namespace config {
}
