// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace config {
    export interface AuthConfig {
        /**
         * The password to use to authenticate to ClickHouse
         */
        password?: string;
        /**
         * The authentication method to use
         */
        strategy: string;
        /**
         * The username to use to authenticate to ClickHouse
         */
        username: string;
    }

    export interface TlsConfig {
        /**
         * Skip TLS cert verification when using the https protocol. This is insecure!
         */
        insecureSkipVerify?: boolean;
    }

}
