# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .database import *
from .grant_privilege import *
from .grant_role import *
from .provider import *
from .role import *
from .setting import *
from .settings_profile import *
from .settings_profile_association import *
from .user import *
from ._inputs import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_clickhousedbops.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_clickhousedbops.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "clickhousedbops",
  "mod": "index/database",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/database:Database": "Database"
  }
 },
 {
  "pkg": "clickhousedbops",
  "mod": "index/grantPrivilege",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/grantPrivilege:GrantPrivilege": "GrantPrivilege"
  }
 },
 {
  "pkg": "clickhousedbops",
  "mod": "index/grantRole",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/grantRole:GrantRole": "GrantRole"
  }
 },
 {
  "pkg": "clickhousedbops",
  "mod": "index/role",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/role:Role": "Role"
  }
 },
 {
  "pkg": "clickhousedbops",
  "mod": "index/setting",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/setting:Setting": "Setting"
  }
 },
 {
  "pkg": "clickhousedbops",
  "mod": "index/settingsProfile",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/settingsProfile:SettingsProfile": "SettingsProfile"
  }
 },
 {
  "pkg": "clickhousedbops",
  "mod": "index/settingsProfileAssociation",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/settingsProfileAssociation:SettingsProfileAssociation": "SettingsProfileAssociation"
  }
 },
 {
  "pkg": "clickhousedbops",
  "mod": "index/user",
  "fqn": "pulumi_clickhousedbops",
  "classes": {
   "clickhousedbops:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "clickhousedbops",
  "token": "pulumi:providers:clickhousedbops",
  "fqn": "pulumi_clickhousedbops",
  "class": "Provider"
 }
]
"""
)
