# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['GrantRoleArgs', 'GrantRole']

@pulumi.input_type
class GrantRoleArgs:
    def __init__(__self__, *,
                 role_name: pulumi.Input[_builtins.str],
                 admin_option: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_user_name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a GrantRole resource.
        :param pulumi.Input[_builtins.str] role_name: Name of the role to be granted
        :param pulumi.Input[_builtins.bool] admin_option: If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        :param pulumi.Input[_builtins.str] cluster_name: Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
               This field must be left null when using a ClickHouse Cloud cluster.
               When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        :param pulumi.Input[_builtins.str] grantee_role_name: Name of the `role` to grant `role_name` to.
        :param pulumi.Input[_builtins.str] grantee_user_name: Name of the `user` to grant `role_name` to.
        """
        pulumi.set(__self__, "role_name", role_name)
        if admin_option is not None:
            pulumi.set(__self__, "admin_option", admin_option)
        if cluster_name is not None:
            pulumi.set(__self__, "cluster_name", cluster_name)
        if grantee_role_name is not None:
            pulumi.set(__self__, "grantee_role_name", grantee_role_name)
        if grantee_user_name is not None:
            pulumi.set(__self__, "grantee_user_name", grantee_user_name)

    @_builtins.property
    @pulumi.getter(name="roleName")
    def role_name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the role to be granted
        """
        return pulumi.get(self, "role_name")

    @role_name.setter
    def role_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role_name", value)

    @_builtins.property
    @pulumi.getter(name="adminOption")
    def admin_option(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        """
        return pulumi.get(self, "admin_option")

    @admin_option.setter
    def admin_option(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "admin_option", value)

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        This field must be left null when using a ClickHouse Cloud cluster.
        When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        """
        return pulumi.get(self, "cluster_name")

    @cluster_name.setter
    def cluster_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster_name", value)

    @_builtins.property
    @pulumi.getter(name="granteeRoleName")
    def grantee_role_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the `role` to grant `role_name` to.
        """
        return pulumi.get(self, "grantee_role_name")

    @grantee_role_name.setter
    def grantee_role_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "grantee_role_name", value)

    @_builtins.property
    @pulumi.getter(name="granteeUserName")
    def grantee_user_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the `user` to grant `role_name` to.
        """
        return pulumi.get(self, "grantee_user_name")

    @grantee_user_name.setter
    def grantee_user_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "grantee_user_name", value)


@pulumi.input_type
class _GrantRoleState:
    def __init__(__self__, *,
                 admin_option: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_user_name: Optional[pulumi.Input[_builtins.str]] = None,
                 role_name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering GrantRole resources.
        :param pulumi.Input[_builtins.bool] admin_option: If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        :param pulumi.Input[_builtins.str] cluster_name: Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
               This field must be left null when using a ClickHouse Cloud cluster.
               When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        :param pulumi.Input[_builtins.str] grantee_role_name: Name of the `role` to grant `role_name` to.
        :param pulumi.Input[_builtins.str] grantee_user_name: Name of the `user` to grant `role_name` to.
        :param pulumi.Input[_builtins.str] role_name: Name of the role to be granted
        """
        if admin_option is not None:
            pulumi.set(__self__, "admin_option", admin_option)
        if cluster_name is not None:
            pulumi.set(__self__, "cluster_name", cluster_name)
        if grantee_role_name is not None:
            pulumi.set(__self__, "grantee_role_name", grantee_role_name)
        if grantee_user_name is not None:
            pulumi.set(__self__, "grantee_user_name", grantee_user_name)
        if role_name is not None:
            pulumi.set(__self__, "role_name", role_name)

    @_builtins.property
    @pulumi.getter(name="adminOption")
    def admin_option(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        """
        return pulumi.get(self, "admin_option")

    @admin_option.setter
    def admin_option(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "admin_option", value)

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        This field must be left null when using a ClickHouse Cloud cluster.
        When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        """
        return pulumi.get(self, "cluster_name")

    @cluster_name.setter
    def cluster_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "cluster_name", value)

    @_builtins.property
    @pulumi.getter(name="granteeRoleName")
    def grantee_role_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the `role` to grant `role_name` to.
        """
        return pulumi.get(self, "grantee_role_name")

    @grantee_role_name.setter
    def grantee_role_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "grantee_role_name", value)

    @_builtins.property
    @pulumi.getter(name="granteeUserName")
    def grantee_user_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the `user` to grant `role_name` to.
        """
        return pulumi.get(self, "grantee_user_name")

    @grantee_user_name.setter
    def grantee_user_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "grantee_user_name", value)

    @_builtins.property
    @pulumi.getter(name="roleName")
    def role_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Name of the role to be granted
        """
        return pulumi.get(self, "role_name")

    @role_name.setter
    def role_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "role_name", value)


@pulumi.type_token("clickhousedbops:index/grantRole:GrantRole")
class GrantRole(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 admin_option: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_user_name: Optional[pulumi.Input[_builtins.str]] = None,
                 role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        ## Example Usage

        ```python
        import pulumi
        import pulumi_clickhousedbops as clickhousedbops

        role_to_user = clickhousedbops.GrantRole("role_to_user",
            cluster_name="cluster",
            role_name="myrole",
            grantee_user_name="myuser")
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] admin_option: If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        :param pulumi.Input[_builtins.str] cluster_name: Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
               This field must be left null when using a ClickHouse Cloud cluster.
               When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        :param pulumi.Input[_builtins.str] grantee_role_name: Name of the `role` to grant `role_name` to.
        :param pulumi.Input[_builtins.str] grantee_user_name: Name of the `user` to grant `role_name` to.
        :param pulumi.Input[_builtins.str] role_name: Name of the role to be granted
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: GrantRoleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        ## Example Usage

        ```python
        import pulumi
        import pulumi_clickhousedbops as clickhousedbops

        role_to_user = clickhousedbops.GrantRole("role_to_user",
            cluster_name="cluster",
            role_name="myrole",
            grantee_user_name="myuser")
        ```

        :param str resource_name: The name of the resource.
        :param GrantRoleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(GrantRoleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 admin_option: Optional[pulumi.Input[_builtins.bool]] = None,
                 cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 grantee_user_name: Optional[pulumi.Input[_builtins.str]] = None,
                 role_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = GrantRoleArgs.__new__(GrantRoleArgs)

            __props__.__dict__["admin_option"] = admin_option
            __props__.__dict__["cluster_name"] = cluster_name
            __props__.__dict__["grantee_role_name"] = grantee_role_name
            __props__.__dict__["grantee_user_name"] = grantee_user_name
            if role_name is None and not opts.urn:
                raise TypeError("Missing required property 'role_name'")
            __props__.__dict__["role_name"] = role_name
        super(GrantRole, __self__).__init__(
            'clickhousedbops:index/grantRole:GrantRole',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            admin_option: Optional[pulumi.Input[_builtins.bool]] = None,
            cluster_name: Optional[pulumi.Input[_builtins.str]] = None,
            grantee_role_name: Optional[pulumi.Input[_builtins.str]] = None,
            grantee_user_name: Optional[pulumi.Input[_builtins.str]] = None,
            role_name: Optional[pulumi.Input[_builtins.str]] = None) -> 'GrantRole':
        """
        Get an existing GrantRole resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] admin_option: If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        :param pulumi.Input[_builtins.str] cluster_name: Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
               This field must be left null when using a ClickHouse Cloud cluster.
               When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        :param pulumi.Input[_builtins.str] grantee_role_name: Name of the `role` to grant `role_name` to.
        :param pulumi.Input[_builtins.str] grantee_user_name: Name of the `user` to grant `role_name` to.
        :param pulumi.Input[_builtins.str] role_name: Name of the role to be granted
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _GrantRoleState.__new__(_GrantRoleState)

        __props__.__dict__["admin_option"] = admin_option
        __props__.__dict__["cluster_name"] = cluster_name
        __props__.__dict__["grantee_role_name"] = grantee_role_name
        __props__.__dict__["grantee_user_name"] = grantee_user_name
        __props__.__dict__["role_name"] = role_name
        return GrantRole(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="adminOption")
    def admin_option(self) -> pulumi.Output[_builtins.bool]:
        """
        If true, the grantee will be able to grant `role_name` to other `users` or `roles`.
        """
        return pulumi.get(self, "admin_option")

    @_builtins.property
    @pulumi.getter(name="clusterName")
    def cluster_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
        This field must be left null when using a ClickHouse Cloud cluster.
        When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
        """
        return pulumi.get(self, "cluster_name")

    @_builtins.property
    @pulumi.getter(name="granteeRoleName")
    def grantee_role_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Name of the `role` to grant `role_name` to.
        """
        return pulumi.get(self, "grantee_role_name")

    @_builtins.property
    @pulumi.getter(name="granteeUserName")
    def grantee_user_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Name of the `user` to grant `role_name` to.
        """
        return pulumi.get(self, "grantee_user_name")

    @_builtins.property
    @pulumi.getter(name="roleName")
    def role_name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the role to be granted
        """
        return pulumi.get(self, "role_name")

