// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhousedbops.Inputs
{

    public sealed class ProviderAuthConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The password to use to authenticate to ClickHouse
        /// </summary>
        [Input("password")]
        public Input<string>? Password { get; set; }

        /// <summary>
        /// The authentication method to use
        /// </summary>
        [Input("strategy", required: true)]
        public Input<string> Strategy { get; set; } = null!;

        /// <summary>
        /// The username to use to authenticate to ClickHouse
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public ProviderAuthConfigArgs()
        {
        }
        public static new ProviderAuthConfigArgs Empty => new ProviderAuthConfigArgs();
    }
}
