// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Clickhousedbops.Inputs
{

    public sealed class ProviderTlsConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Skip TLS cert verification when using the https protocol. This is insecure!
        /// </summary>
        [Input("insecureSkipVerify")]
        public Input<bool>? InsecureSkipVerify { get; set; }

        public ProviderTlsConfigArgs()
        {
        }
        public static new ProviderTlsConfigArgs Empty => new ProviderTlsConfigArgs();
    }
}
