// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use the *clickhousedbops_database* resource to create a database in a ClickHouse instance.
 *
 * Known limitations:
 *
 * - Changing the comment on a `database` resource is unsupported and will cause the database to be destroyed and recreated. WARNING: you will lose any content of the database if you do so!
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as clickhousedbops from "@pulumi/clickhousedbops";
 *
 * const logs = new clickhousedbops.Database("logs", {
 *     clusterName: "cluster",
 *     name: "logs",
 * });
 * ```
 *
 * ## Import
 *
 * Databases can be imported by specifying the UUID.
 *
 * Find the UUID of the database by checking system.databases table.
 *
 * ```sh
 * $ pulumi import clickhousedbops:index/database:Database example xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 * ```
 *
 * It's also possible to import databases using the name:
 *
 * ```sh
 * $ pulumi import clickhousedbops:index/database:Database example databasename
 * ```
 *
 * IMPORTANT: if you have a multi node cluster, you need to specify the cluster name!
 *
 * ```sh
 * $ pulumi import clickhousedbops:index/database:Database example cluster:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 * ```
 *
 * ```sh
 * $ pulumi import clickhousedbops:index/database:Database example cluster:databasename
 * ```
 */
export class Database extends pulumi.CustomResource {
    /**
     * Get an existing Database resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DatabaseState, opts?: pulumi.CustomResourceOptions): Database {
        return new Database(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'clickhousedbops:index/database:Database';

    /**
     * Returns true if the given object is an instance of Database.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Database {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Database.__pulumiType;
    }

    /**
     * Name of the cluster to create the database into. If omitted, the database will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * Should be set when hitting a cluster with more than one replica.
     */
    public readonly clusterName!: pulumi.Output<string | undefined>;
    /**
     * Comment associated with the database
     */
    public readonly comment!: pulumi.Output<string | undefined>;
    /**
     * Name of the database
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The system-assigned UUID for the database
     */
    public /*out*/ readonly uuid!: pulumi.Output<string>;

    /**
     * Create a Database resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DatabaseArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DatabaseArgs | DatabaseState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DatabaseState | undefined;
            resourceInputs["clusterName"] = state ? state.clusterName : undefined;
            resourceInputs["comment"] = state ? state.comment : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["uuid"] = state ? state.uuid : undefined;
        } else {
            const args = argsOrState as DatabaseArgs | undefined;
            resourceInputs["clusterName"] = args ? args.clusterName : undefined;
            resourceInputs["comment"] = args ? args.comment : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Database.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Database resources.
 */
export interface DatabaseState {
    /**
     * Name of the cluster to create the database into. If omitted, the database will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * Should be set when hitting a cluster with more than one replica.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment associated with the database
     */
    comment?: pulumi.Input<string>;
    /**
     * Name of the database
     */
    name?: pulumi.Input<string>;
    /**
     * The system-assigned UUID for the database
     */
    uuid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Database resource.
 */
export interface DatabaseArgs {
    /**
     * Name of the cluster to create the database into. If omitted, the database will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * Should be set when hitting a cluster with more than one replica.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Comment associated with the database
     */
    comment?: pulumi.Input<string>;
    /**
     * Name of the database
     */
    name?: pulumi.Input<string>;
}
