// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as clickhousedbops from "@pulumi/clickhousedbops";
 *
 * const roleToUser = new clickhousedbops.GrantRole("role_to_user", {
 *     clusterName: "cluster",
 *     roleName: "myrole",
 *     granteeUserName: "myuser",
 * });
 * ```
 */
export class GrantRole extends pulumi.CustomResource {
    /**
     * Get an existing GrantRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GrantRoleState, opts?: pulumi.CustomResourceOptions): GrantRole {
        return new GrantRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'clickhousedbops:index/grantRole:GrantRole';

    /**
     * Returns true if the given object is an instance of GrantRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GrantRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GrantRole.__pulumiType;
    }

    /**
     * If true, the grantee will be able to grant `roleName` to other `users` or `roles`.
     */
    public readonly adminOption!: pulumi.Output<boolean>;
    /**
     * Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
     */
    public readonly clusterName!: pulumi.Output<string | undefined>;
    /**
     * Name of the `role` to grant `roleName` to.
     */
    public readonly granteeRoleName!: pulumi.Output<string | undefined>;
    /**
     * Name of the `user` to grant `roleName` to.
     */
    public readonly granteeUserName!: pulumi.Output<string | undefined>;
    /**
     * Name of the role to be granted
     */
    public readonly roleName!: pulumi.Output<string>;

    /**
     * Create a GrantRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GrantRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GrantRoleArgs | GrantRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GrantRoleState | undefined;
            resourceInputs["adminOption"] = state ? state.adminOption : undefined;
            resourceInputs["clusterName"] = state ? state.clusterName : undefined;
            resourceInputs["granteeRoleName"] = state ? state.granteeRoleName : undefined;
            resourceInputs["granteeUserName"] = state ? state.granteeUserName : undefined;
            resourceInputs["roleName"] = state ? state.roleName : undefined;
        } else {
            const args = argsOrState as GrantRoleArgs | undefined;
            if ((!args || args.roleName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'roleName'");
            }
            resourceInputs["adminOption"] = args ? args.adminOption : undefined;
            resourceInputs["clusterName"] = args ? args.clusterName : undefined;
            resourceInputs["granteeRoleName"] = args ? args.granteeRoleName : undefined;
            resourceInputs["granteeUserName"] = args ? args.granteeUserName : undefined;
            resourceInputs["roleName"] = args ? args.roleName : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GrantRole.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GrantRole resources.
 */
export interface GrantRoleState {
    /**
     * If true, the grantee will be able to grant `roleName` to other `users` or `roles`.
     */
    adminOption?: pulumi.Input<boolean>;
    /**
     * Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Name of the `role` to grant `roleName` to.
     */
    granteeRoleName?: pulumi.Input<string>;
    /**
     * Name of the `user` to grant `roleName` to.
     */
    granteeUserName?: pulumi.Input<string>;
    /**
     * Name of the role to be granted
     */
    roleName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a GrantRole resource.
 */
export interface GrantRoleArgs {
    /**
     * If true, the grantee will be able to grant `roleName` to other `users` or `roles`.
     */
    adminOption?: pulumi.Input<boolean>;
    /**
     * Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Name of the `role` to grant `roleName` to.
     */
    granteeRoleName?: pulumi.Input<string>;
    /**
     * Name of the `user` to grant `roleName` to.
     */
    granteeUserName?: pulumi.Input<string>;
    /**
     * Name of the role to be granted
     */
    roleName: pulumi.Input<string>;
}
