// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * You can use the `clickhousedbops.Setting` resource to manage the single `settings` of a `Setting Profile` in a `ClickHouse` instance.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as clickhousedbops from "@pulumi/clickhousedbops";
 *
 * const setting1 = new clickhousedbops.Setting("setting1", {
 *     settingsProfileId: profile1.id,
 *     name: "max_memory_usage",
 *     value: "1000",
 *     min: "100",
 *     max: "2000",
 *     writability: "CHANGEABLE_IN_READONLY",
 * });
 * ```
 */
export class Setting extends pulumi.CustomResource {
    /**
     * Get an existing Setting resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SettingState, opts?: pulumi.CustomResourceOptions): Setting {
        return new Setting(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'clickhousedbops:index/setting:Setting';

    /**
     * Returns true if the given object is an instance of Setting.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Setting {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Setting.__pulumiType;
    }

    /**
     * Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
     */
    public readonly clusterName!: pulumi.Output<string | undefined>;
    /**
     * Max Value for the setting
     */
    public readonly max!: pulumi.Output<string | undefined>;
    /**
     * Min Value for the setting
     */
    public readonly min!: pulumi.Output<string | undefined>;
    /**
     * Name of the setting
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * ID of the settings profile
     */
    public readonly settingsProfileId!: pulumi.Output<string>;
    /**
     * Value for the setting
     */
    public readonly value!: pulumi.Output<string | undefined>;
    /**
     * Writability attribute for the setting
     */
    public readonly writability!: pulumi.Output<string | undefined>;

    /**
     * Create a Setting resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SettingArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SettingArgs | SettingState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SettingState | undefined;
            resourceInputs["clusterName"] = state ? state.clusterName : undefined;
            resourceInputs["max"] = state ? state.max : undefined;
            resourceInputs["min"] = state ? state.min : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["settingsProfileId"] = state ? state.settingsProfileId : undefined;
            resourceInputs["value"] = state ? state.value : undefined;
            resourceInputs["writability"] = state ? state.writability : undefined;
        } else {
            const args = argsOrState as SettingArgs | undefined;
            if ((!args || args.settingsProfileId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'settingsProfileId'");
            }
            resourceInputs["clusterName"] = args ? args.clusterName : undefined;
            resourceInputs["max"] = args ? args.max : undefined;
            resourceInputs["min"] = args ? args.min : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["settingsProfileId"] = args ? args.settingsProfileId : undefined;
            resourceInputs["value"] = args ? args.value : undefined;
            resourceInputs["writability"] = args ? args.writability : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Setting.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Setting resources.
 */
export interface SettingState {
    /**
     * Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Max Value for the setting
     */
    max?: pulumi.Input<string>;
    /**
     * Min Value for the setting
     */
    min?: pulumi.Input<string>;
    /**
     * Name of the setting
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the settings profile
     */
    settingsProfileId?: pulumi.Input<string>;
    /**
     * Value for the setting
     */
    value?: pulumi.Input<string>;
    /**
     * Writability attribute for the setting
     */
    writability?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Setting resource.
 */
export interface SettingArgs {
    /**
     * Name of the cluster to create the resource into. If omitted, resource will be created on the replica hit by the query.
     * This field must be left null when using a ClickHouse Cloud cluster.
     * When using a self hosted ClickHouse instance, this field should only be set when there is more than one replica and you are not using 'replicated' storage for user_directory.
     */
    clusterName?: pulumi.Input<string>;
    /**
     * Max Value for the setting
     */
    max?: pulumi.Input<string>;
    /**
     * Min Value for the setting
     */
    min?: pulumi.Input<string>;
    /**
     * Name of the setting
     */
    name?: pulumi.Input<string>;
    /**
     * ID of the settings profile
     */
    settingsProfileId: pulumi.Input<string>;
    /**
     * Value for the setting
     */
    value?: pulumi.Input<string>;
    /**
     * Writability attribute for the setting
     */
    writability?: pulumi.Input<string>;
}
